### ISSUE TITLE
Plan Builder: Style Plan Builder to match mocks

### ISSUE THREAD

**Issue by iangmhill** [MAPC/roadworks#15]
The Plan Builder should be styled according to the designs created by @ericyoungberg.

**Comment by ericyoungberg** [comment]
[Roadworks-FirstMocks.pdf](https://github.com/MAPC/roadworks/files/1856404/Roadworks-FirstMocks.pdf)

**Comment by ericyoungberg** [comment]
This issue finished awhile ago. So far ago that it would be an endeavor finding the exact commit wear I finished the styling.
